dic = {
    "FILE_OPEN": _("開く"),
    "FILE_SAVE": _("上書き保存"),
    "FILE_SAVEAS": _("名前を付けて保存"),
    "FILE_EXIT": _("終了"),
    "EDIT_OPENNODE": _("開く"),
    "EDIT_DELETENODE": _("削除"),
    "INSERT_MESSAGE": _("メッセージを表示"),
    "INSERT_QUESTION_BRANCH": _("「はい/いいえ」で分岐"),
    "INSERT_FIFTY_FIFTY_BRANCH": _("ランダムで2つに分岐"),
    "INSERT_WAIT": _("一定時間待つ"),
    "MOVE_LEAVE": _("一つ上の階層へ"),
    "EXEC_RUN": _("実行"),
    "EXEC_OUTPUTPROGRAM": _("Python コードを出力"),
    "HELP_UPDATE": _("最新バージョンを確認(&U)") + "...",
    "HELP_VERSIONINFO": _("バージョン情報(&V)") + "...",
}
