# -*- coding: utf-8 -*-

import unittest
from node.root import *
from node.print import *
from block import Block


class TestCodegen(unittest.TestCase):
    def test_print(self):
        r = RootNode()
        p = PrintNode()
        p.setSingleParameter("message", "hello")
        blk = Block()
        blk.append(p)
        r.setSingleChildBlock("block", blk)
        generated = r.generate()
        self.assertEqual(generated[0], "# generated by nyancode.")
        self.assertEqual(generated[1], "print(\"hello\")")
