from .base import *


class RootNode(BaseNode):
    """プログラム全体を表すノード。"""
    parameter_constraints = {}
    child_blocks = {
        "block"  # 処理本体
    }

    def generate(self, indent_level=0):
        ret = ["# generated by nyancode."]
        for elem in self.child_blocks["block"]:
            ret.extend(elem.generate(indent_level))
        # end for
        return ret
